In [1]:
import pandas as pd

In [2]:
data_movie_gross = pd.read_csv('zippedData/bom.movie_gross.csv.gz')

In [3]:
data_title_ratings = pd.read_csv('zippedData/imdb.title.ratings.csv.gz')

In [9]:
data_title_ratings.head()

       tconst  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21

In [10]:
data_title_basics = pd.read_csv('zippedData/imdb.title.basics.csv.gz')

In [11]:
data_title_basics.head()

,tconst,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"

In [13]:
## Merged imdb.title.basics.csv.gz and imdb.title.ratings.csv.gz on the column 'tconst' with an inner join to eliminate 
## non-matching items.
data_title_overall = pd.merge(data_title_basics, data_title_ratings, on='tconst', how='inner')

In [14]:
## Renamed 'primary_title' to 'title' in order to smoothly merge this dataframe with bom.movie_gross.csv.gz.
data_title_overall = data_title_overall.rename(columns={'primary_title': 'title'})

In [28]:
## Merged IMDB and BOM data into one dataframe
movie_titles = pd.merge(data_movie_gross, data_title_overall, on='title', how='inner')

In [29]:
movie_titles.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3027 entries, 0 to 3026
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            3027 non-null   object
 1   studio           3024 non-null   object
 2   domestic_gross   3005 non-null   float64
 3   foreign_gross    1832 non-null   object
 4   year             3027 non-null   int64
 5   tconst           3027 non-null   object
 6   original_title   3027 non-null   object
 7   start_year       3027 non-null   int64
 8   runtime_minutes  2980 non-null   float64
 9   genres           3020 non-null   object
 10  averagerating    3027 non-null   float64
 11  numvotes         3027 non-null   int64
dtypes: float64(3), int64(3), object(6)
memory usage: 307.4+ KB

In [17]:
movie_titles = movie_titles[['title', 'studio', 'domestic_gross', 'foreign_gross', 'year', 'genres', 'averagerating']]

In [18]:
movie_titles.dropna(axis=0, how='any', inplace=True)

In [30]:
movie_titles['foreign_gross'] = movie_titles.foreign_gross.str.split(',').str.join('').astype(float)

In [31]:
movie_titles['total_gross'] = movie_titles['domestic_gross'] + movie_titles['foreign_gross']

In [32]:
movie_titles.head()

,title,studio,domestic_gross,foreign_gross,year,tconst,original_title,start_year,runtime_minutes,genres,averagerating,numvotes,total_gross
0,Toy Story 3,BV,415000000.0,652000000.0,2010,tt0435761,Toy Story 3,2010,103.0,"Adventure,Animation,Comedy",8.3,682218,1.067000e+09
1,Inception,WB,292600000.0,535700000.0,2010,tt1375666,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,8.283000e+08
2,Shrek Forever After,P/DW,238700000.0,513900000.0,2010,tt0892791,Shrek Forever After,2010,93.0,"Adventure,Animation,Comedy",6.3,167532,7.526000e+08
3,The Twilight Saga: Eclipse,Sum.,300500000.0,398000000.0,2010,tt1325004,The Twilight Saga: Eclipse,2010,124.0,"Adventure,Drama,Fantasy",5.0,211733,6.985000e+08
4,Iron Man 2,Par.,312400000.0,311500000.0,2010,tt1228705,Iron Man 2,2010,124.0,"Action,Adventure,Sci-Fi",7.0,657690,6.239000e+08

In [22]:
movie_genres = movie_titles[['title', 'genres']]

In [23]:
movie_genres.head()

                        title                      genres
0                 Toy Story 3  Adventure,Animation,Comedy
1                   Inception     Action,Adventure,Sci-Fi
2         Shrek Forever After  Adventure,Animation,Comedy
3  The Twilight Saga: Eclipse     Adventure,Drama,Fantasy
4                  Iron Man 2     Action,Adventure,Sci-Fi

In [24]:
df_unique = movie_genres.genres.unique()

In [25]:
print(df_unique)

['Adventure,Animation,Comedy' 'Action,Adventure,Sci-Fi'
 'Adventure,Drama,Fantasy' 'Animation,Comedy,Family'
 'Action,Adventure,Animation' 'Adventure,Family,Fantasy'
 'Biography,Drama,History' 'Action,Drama,Family'
 'Action,Adventure,Fantasy' 'Drama,Thriller' 'Action,Animation,Comedy'
 'Action,Adventure,Drama' 'Action,Drama' 'Action,Adventure,Thriller'
 'Action,Adventure,Family' 'Comedy,Romance' 'Action,Adventure,Horror'
 'Mystery,Thriller' 'Action,Mystery,Thriller' 'Comedy,Drama,Romance'
 'Comedy' 'Adventure,Drama,Western' 'Adventure,Comedy,Family'
 'Biography,Drama' 'Adventure,Comedy' 'Drama,Romance' 'Thriller' 'Drama'
 'Horror' 'Action,Comedy,Crime' 'Action,Thriller' 'Documentary'
 'Action,Crime' 'Crime,Drama,Thriller' 'Comedy,Crime,Romance'
 'Drama,Fantasy,Horror' 'Action,Comedy,Romance' 'Biography,Drama,Sport'
 'Drama,Romance,War' 'Action,Comedy,Family' 'Comedy,Family,Fantasy'
 'Drama,Fantasy,Romance' 'Crime,Drama,Mystery' 'Action,Crime,Drama'
 'Action,Comedy' 'Action,Drama,Thriller' 'Adventure,Comedy,Music'
 'Drama,Music,Musical' 'Drama,Music,Romance' 'Comedy,Family'
 'Comedy,Horror' 'Adventure,Comedy,Drama' 'Comedy,Drama,Family'
 'Action,Crime,Thriller' 'Drama,Horror,Thriller' 'Action,Sci-Fi,Thriller'
 'Comedy,Sci-Fi' 'Horror,Mystery,Thriller' 'Adventure,Biography,Drama'
 'Biography,Drama,Family' 'Drama,Mystery,Thriller' 'Horror,Thriller'
 'Action,Comedy,Fantasy' 'Comedy,Family,Romance' 'Action,Adventure,Crime'
 'Comedy,Romance,Sport' 'Drama,Music' 'Comedy,Drama' 'Action,Crime,Sci-Fi'
 'Action,Family,Fantasy' 'Drama,Mystery' 'Crime,Drama'
 'Biography,Comedy,Drama' 'Action,Fantasy,Western' 'Action,Drama,Fantasy'
 'Crime,Horror,Mystery' 'Biography,Crime,Drama' 'Drama,Romance,Sci-Fi'
 'Crime,Documentary' 'Biography,Documentary' 'Comedy,Crime,Documentary'
 'Biography,Drama,Music' 'Adventure' 'Comedy,Crime,Drama'
 'Drama,Sci-Fi,Thriller' 'Adventure,Fantasy,Horror' 'Crime,Drama,Horror'
 'Documentary,Drama,Mystery' 'Action,Drama,Romance' 'Drama,Family'
 'Family,Sport' 'Comedy,Crime' 'Family' 'Comedy,Drama,Musical'
 'Documentary,War' 'Biography,Drama,Romance' 'Action,Fantasy,Horror'
 'Biography,Comedy,Crime' 'Comedy,Drama,Music' 'Drama,Romance,Thriller'
 'Comedy,Drama,Fantasy' 'Thriller,Western' 'Documentary,History'
 'Crime,Thriller' 'Comedy,Mystery' 'Action,Drama,Sci-Fi'
 'Mystery,Sci-Fi,Thriller' 'Adventure,Drama,Family' 'Drama,History,War'
 'Action,Adventure,Comedy' 'Comedy,Fantasy,Romance'
 'Romance,Sci-Fi,Thriller' 'Adventure,Drama,Thriller' 'Documentary,Music'
 'Adventure,Comedy,Sci-Fi' 'Horror,Mystery' 'Drama,Horror,Mystery'
 'Fantasy,Horror,Mystery' 'Action,Comedy,Drama' 'Action,Sci-Fi'
 'Comedy,Fantasy' 'Documentary,News' 'Drama,Fantasy' 'Drama,History'
 'Adventure,Drama,Mystery' 'Action' 'Adventure,Animation,Family'
 'Fantasy,Horror,Thriller' 'Adventure,Documentary'
 'Action,Fantasy,Thriller' 'Action,Drama,History' 'Horror,Mystery,Sci-Fi'
 'Adventure,Comedy,Fantasy' 'Drama,Sport' 'Drama,War'
 'Adventure,Drama,History' 'Documentary,Drama,Family'
 'Comedy,Crime,Thriller' 'Animation,Comedy,Crime' 'Drama,Sci-Fi'
 'Drama,Mystery,Romance' 'Crime,Drama,History' 'Horror,Romance'
 'Comedy,Drama,Sport' 'Adventure,Comedy,Western'
 'Crime,Documentary,History' 'Biography,Documentary,Sport'
 'Action,Comedy,Sci-Fi' 'Comedy,Crime,History' 'Crime,Drama,Romance'
 'Comedy,Drama,Mystery' 'Action,Biography,Crime' 'Comedy,Drama,Horror'
 'Comedy,Crime,Mystery' 'Animation,Drama' 'Action,Adventure,Western'
 'Comedy,Mystery,Romance' 'Romance,Thriller' 'Biography,Documentary,Drama'
 'Drama,Western' 'Adventure,Mystery,Sci-Fi' 'Comedy,Fantasy,Horror'
 'Action,Horror,Sci-Fi' 'Biography,Drama,Thriller'
 'Drama,History,Thriller' 'Action,Drama,Mystery' 'Comedy,Music,Romance'
 'Action,Comedy,Western' 'Action,Comedy,Sport' 'Action,Comedy,Horror'
 'Fantasy,Romance' 'Action,Crime,Mystery' 'Crime,Mystery,Thriller'
 'Action,History' 'Adventure,Drama,Romance' 'Drama,History,Romance'
 'Drama,Fantasy,Thriller' 'Drama,Mystery,Western'
 'Animation,Comedy,Fantasy' 'Comedy,Mystery,Thriller'
 'Animation,Crime,Drama' 'Biography,Crime,Documentary' 'Animation,Fantasy'
 'Fantasy' 'Drama,Thriller,War' 'Action,Horror,Mystery'
 'Biography,Documentary,History' 'Adventure,Drama,Sport'
 'Adventure,Fantasy' 'Adventure,Comedy,Crime' 'Action,Biography,Drama'
 'Comedy,Horror,Romance' 'Animation,Drama,Family' 'Comedy,Documentary'
 'Horror,Sci-Fi,Thriller' 'Adventure,History' 'Mystery' 'Biography,Comedy'
 'Drama,Horror' 'Music' 'Drama,Family,Music' 'Action,Fantasy,Romance'
 'Action,Adventure' 'Adventure,Drama,Sci-Fi' 'Animation'
 'Action,Mystery,Sci-Fi' 'Action,Adventure,Mystery' 'Comedy,Musical'
 'Action,Sport,War' 'Comedy,Drama,History' 'Animation,Biography,Drama'
 'Comedy,Western' 'Drama,Fantasy,Music' 'Action,Animation,Drama'
 'Adventure,Family,Sci-Fi' 'Drama,Fantasy,Mystery'
 'Adventure,Animation,Drama' 'Crime,Drama,Fantasy'
 'Biography,Documentary,Thriller' 'Documentary,Drama,Music'
 'Drama,Musical,Romance' 'Comedy,Thriller' 'Animation,Drama,Sci-Fi'
 'Adventure,Crime,Drama' 'Action,Adventure,Biography' 'Comedy,Music'
 'Adventure,Drama' 'Adventure,Biography,Comedy' 'Drama,Mystery,Sci-Fi'
 'Drama,Horror,Sci-Fi' 'Comedy,Drama,Thriller' 'Fantasy,Horror'
 'Comedy,Mystery,Sci-Fi' 'Mystery,Romance,Thriller'
 'Animation,Comedy,Drama' 'Biography,Documentary,Music'
 'Crime,Horror,Thriller' 'Action,Horror,Thriller' 'Action,Drama,Sport'
 'Adventure,Comedy,Romance' 'Animation,Drama,Fantasy' 'Comedy,Drama,War'
 'Sci-Fi' 'Documentary,Drama,Sport' 'Biography,Drama,Musical' 'Crime'
 'Action,Comedy,Thriller' 'Action,Biography,Comedy' 'Action,Comedy,War'
 'Animation,Biography,Crime' 'Drama,History,Sport' 'Documentary,Family'
 'Action,Sport' 'Action,Comedy,Mystery' 'Comedy,Musical,Romance'
 'Horror,Romance,Thriller' 'Romance' 'Adventure,Comedy,Horror'
 'Comedy,Sport' 'Comedy,History' 'Biography,Drama,War' 'Fantasy,Thriller']

In [33]:
df_unique[0]

'Adventure,Animation,Comedy'

In [36]:
df_unique[0].split(',')

['Adventure', 'Animation', 'Comedy']

In [38]:
df_unique[0].split(',')[1]

'Animation'

In [45]:
movie_genres_list = []

for x in df_unique:
    movie_genres_list.extend(x.split(','))

In [50]:
movie_genres_list

['Adventure',
 'Animation',
 'Comedy',
 'Action',
 'Adventure',
 'Sci-Fi',
 'Adventure',
 'Drama',
 'Fantasy',
 'Animation',
 'Comedy',
 'Family',
 'Action',
 'Adventure',
 'Animation',
 'Adventure',
 'Family',
 'Fantasy',
 'Biography',
 'Drama',
 'History',
 'Action',
 'Drama',
 'Family',
 'Action',
 'Adventure',
 'Fantasy',
 'Drama',
 'Thriller',
 'Action',
 'Animation',
 'Comedy',
 'Action',
 'Adventure',
 'Drama',
 'Action',
 'Drama',
 'Action',
 'Adventure',
 'Thriller',
 'Action',
 'Adventure',
 'Family',
 'Comedy',
 'Romance',
 'Action',
 'Adventure',
 'Horror',
 'Mystery',
 'Thriller',
 'Action',
 'Mystery',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Adventure',
 'Drama',
 'Western',
 'Adventure',
 'Comedy',
 'Family',
 'Biography',
 'Drama',
 'Adventure',
 'Comedy',
 'Drama',
 'Romance',
 'Thriller',
 'Drama',
 'Horror',
 'Action',
 'Comedy',
 'Crime',
 'Action',
 'Thriller',
 'Documentary',
 'Action',
 'Crime',
 'Crime',
 'Drama',
 'Thriller',
 'Comedy',
 'Crime',
 'Romance',
 'Drama',
 'Fantasy',
 'Horror',
 'Action',
 'Comedy',
 'Romance',
 'Biography',
 'Drama',
 'Sport',
 'Drama',
 'Romance',
 'War',
 'Action',
 'Comedy',
 'Family',
 'Comedy',
 'Family',
 'Fantasy',
 'Drama',
 'Fantasy',
 'Romance',
 'Crime',
 'Drama',
 'Mystery',
 'Action',
 'Crime',
 'Drama',
 'Action',
 'Comedy',
 'Action',
 'Drama',
 'Thriller',
 'Adventure',
 'Comedy',
 'Music',
 'Drama',
 'Music',
 'Musical',
 'Drama',
 'Music',
 'Romance',
 'Comedy',
 'Family',
 'Comedy',
 'Horror',
 'Adventure',
 'Comedy',
 'Drama',
 'Comedy',
 'Drama',
 'Family',
 'Action',
 'Crime',
 'Thriller',
 'Drama',
 'Horror',
 'Thriller',
 'Action',
 'Sci-Fi',
 'Thriller',
 'Comedy',
 'Sci-Fi',
 'Horror',
 'Mystery',
 'Thriller',
 'Adventure',
 'Biography',
 'Drama',
 'Biography',
 'Drama',
 'Family',
 'Drama',
 'Mystery',
 'Thriller',
 'Horror',
 'Thriller',
 'Action',
 'Comedy',
 'Fantasy',
 'Comedy',
 'Family',
 'Romance',
 'Action',
 'Adventure',
 'Crime',
 'Comedy',
 'Romance',
 'Sport',
 'Drama',
 'Music',
 'Comedy',
 'Drama',
 'Action',
 'Crime',
 'Sci-Fi',
 'Action',
 'Family',
 'Fantasy',
 'Drama',
 'Mystery',
 'Crime',
 'Drama',
 'Biography',
 'Comedy',
 'Drama',
 'Action',
 'Fantasy',
 'Western',
 'Action',
 'Drama',
 'Fantasy',
 'Crime',
 'Horror',
 'Mystery',
 'Biography',
 'Crime',
 'Drama',
 'Drama',
 'Romance',
 'Sci-Fi',
 'Crime',
 'Documentary',
 'Biography',
 'Documentary',
 'Comedy',
 'Crime',
 'Documentary',
 'Biography',
 'Drama',
 'Music',
 'Adventure',
 'Comedy',
 'Crime',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Thriller',
 'Adventure',
 'Fantasy',
 'Horror',
 'Crime',
 'Drama',
 'Horror',
 'Documentary',
 'Drama',
 'Mystery',
 'Action',
 'Drama',
 'Romance',
 'Drama',
 'Family',
 'Family',
 'Sport',
 'Comedy',
 'Crime',
 'Family',
 'Comedy',
 'Drama',
 'Musical',
 'Documentary',
 'War',
 'Biography',
 'Drama',
 'Romance',
 'Action',
 'Fantasy',
 'Horror',
 'Biography',
 'Comedy',
 'Crime',
 'Comedy',
 'Drama',
 'Music',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Drama',
 'Fantasy',
 'Thriller',
 'Western',
 'Documentary',
 'History',
 'Crime',
 'Thriller',
 'Comedy',
 'Mystery',
 'Action',
 'Drama',
 'Sci-Fi',
 'Mystery',
 'Sci-Fi',
 'Thriller',
 'Adventure',
 'Drama',
 'Family',
 'Drama',
 'History',
 'War',
 'Action',
 'Adventure',
 'Comedy',
 'Comedy',
 'Fantasy',
 'Romance',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'Adventure',
 'Drama',
 'Thriller',
 'Documentary',
 'Music',
 'Adventure',
 'Comedy',
 'Sci-Fi',
 'Horror',
 'Mystery',
 'Drama',
 'Horror',
 'Mystery',
 'Fantasy',
 'Horror',
 'Mystery',
 'Action',
 'Comedy',
 'Drama',
 'Action',
 'Sci-Fi',
 'Comedy',
 'Fantasy',
 'Documentary',
 'News',
 'Drama',
 'Fantasy',
 'Drama',
 'History',
 'Adventure',
 'Drama',
 'Mystery',
 'Action',
 'Adventure',
 'Animation',
 'Family',
 'Fantasy',
 'Horror',
 'Thriller',
 'Adventure',
 'Documentary',
 'Action',
 'Fantasy',
 'Thriller',
 'Action',
 'Drama',
 'History',
 'Horror',
 'Mystery',
 'Sci-Fi',
 'Adventure',
 'Comedy',
 'Fantasy',
 'Drama',
 'Sport',
 'Drama',
 'War',
 'Adventure',
 'Drama',
 'History',
 'Documentary',
 'Drama',
 'Family',
 'Comedy',
 'Crime',
 'Thriller',
 'Animation',
 'Comedy',
 'Crime',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Mystery',
 'Romance',
 'Crime',
 'Drama',
 'History',
 'Horror',
 'Romance',
 'Comedy',
 'Drama',
 'Sport',
 'Adventure',
 'Comedy',
 'Western',
 'Crime',
 'Documentary',
 'History',
 'Biography',
 'Documentary',
 'Sport',
 'Action',
 'Comedy',
 'Sci-Fi',
 'Comedy',
 'Crime',
 'History',
 'Crime',
 'Drama',
 'Romance',
 'Comedy',
 'Drama',
 'Mystery',
 'Action',
 'Biography',
 'Crime',
 'Comedy',
 'Drama',
 'Horror',
 'Comedy',
 'Crime',
 'Mystery',
 'Animation',
 'Drama',
 'Action',
 'Adventure',
 'Western',
 'Comedy',
 'Mystery',
 'Romance',
 'Romance',
 'Thriller',
 'Biography',
 'Documentary',
 'Drama',
 'Drama',
 'Western',
 'Adventure',
 'Mystery',
 'Sci-Fi',
 'Comedy',
 'Fantasy',
 'Horror',
 'Action',
 'Horror',
 'Sci-Fi',
 'Biography',
 'Drama',
 'Thriller',
 'Drama',
 'History',
 'Thriller',
 'Action',
 'Drama',
 'Mystery',
 'Comedy',
 'Music',
 'Romance',
 'Action',
 'Comedy',
 'Western',
 'Action',
 'Comedy',
 'Sport',
 'Action',
 'Comedy',
 'Horror',
 'Fantasy',
 'Romance',
 'Action',
 'Crime',
 'Mystery',
 'Crime',
 'Mystery',
 'Thriller',
 'Action',
 'History',
 'Adventure',
 'Drama',
 'Romance',
 'Drama',
 'History',
 'Romance',
 'Drama',
 'Fantasy',
 'Thriller',
 'Drama',
 'Mystery',
 'Western',
 'Animation',
 'Comedy',
 'Fantasy',
 'Comedy',
 'Mystery',
 'Thriller',
 'Animation',
 'Crime',
 'Drama',
 'Biography',
 'Crime',
 'Documentary',
 'Animation',
 'Fantasy',
 'Fantasy',
 'Drama',
 'Thriller',
 'War',
 'Action',
 'Horror',
 'Mystery',
 'Biography',
 'Documentary',
 'History',
 'Adventure',
 'Drama',
 'Sport',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Comedy',
 'Crime',
 'Action',
 'Biography',
 'Drama',
 'Comedy',
 'Horror',
 'Romance',
 'Animation',
 'Drama',
 'Family',
 'Comedy',
 'Documentary',
 'Horror',
 'Sci-Fi',
 'Thriller',
 'Adventure',
 'History',
 'Mystery',
 'Biography',
 'Comedy',
 'Drama',
 'Horror',
 'Music',
 'Drama',
 'Family',
 'Music',
 'Action',
 'Fantasy',
 'Romance',
 'Action',
 'Adventure',
 'Adventure',
 'Drama',
 'Sci-Fi',
 'Animation',
 'Action',
 'Mystery',
 'Sci-Fi',
 'Action',
 'Adventure',
 'Mystery',
 'Comedy',
 'Musical',
 'Action',
 'Sport',
 'War',
 'Comedy',
 'Drama',
 'History',
 'Animation',
 'Biography',
 'Drama',
 'Comedy',
 'Western',
 'Drama',
 'Fantasy',
 'Music',
 'Action',
 'Animation',
 'Drama',
 'Adventure',
 'Family',
 'Sci-Fi',
 'Drama',
 'Fantasy',
 'Mystery',
 'Adventure',
 'Animation',
 'Drama',
 'Crime',
 'Drama',
 'Fantasy',
 'Biography',
 'Documentary',
 'Thriller',
 'Documentary',
 'Drama',
 'Music',
 'Drama',
 'Musical',
 'Romance',
 'Comedy',
 'Thriller',
 'Animation',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Crime',
 'Drama',
 'Action',
 'Adventure',
 'Biography',
 'Comedy',
 'Music',
 'Adventure',
 'Drama',
 'Adventure',
 'Biography',
 'Comedy',
 'Drama',
 'Mystery',
 'Sci-Fi',
 'Drama',
 'Horror',
 'Sci-Fi',
 'Comedy',
 'Drama',
 'Thriller',
 'Fantasy',
 'Horror',
 'Comedy',
 'Mystery',
 'Sci-Fi',
 'Mystery',
 'Romance',
 'Thriller',
 'Animation',
 'Comedy',
 'Drama',
 'Biography',
 'Documentary',
 'Music',
 'Crime',
 'Horror',
 'Thriller',
 'Action',
 'Horror',
 'Thriller',
 'Action',
 'Drama',
 'Sport',
 'Adventure',
 'Comedy',
 'Romance',
 'Animation',
 'Drama',
 'Fantasy',
 'Comedy',
 'Drama',
 'War',
 'Sci-Fi',
 'Documentary',
 'Drama',
 'Sport',
 'Biography',
 'Drama',
 'Musical',
 'Crime',
 'Action',
 'Comedy',
 'Thriller',
 'Action',
 'Biography',
 'Comedy',
 'Action',
 'Comedy',
 'War',
 'Animation',
 'Biography',
 'Crime',
 'Drama',
 'History',
 'Sport',
 'Documentary',
 'Family',
 'Action',
 'Sport',
 'Action',
 'Comedy',
 'Mystery',
 'Comedy',
 'Musical',
 'Romance',
 'Horror',
 'Romance',
 'Thriller',
 'Romance',
 'Adventure',
 'Comedy',
 'Horror',
 'Comedy',
 'Sport',
 'Comedy',
 'History',
 'Biography',
 'Drama',
 'War',
 'Fantasy',
 'Thriller']

In [55]:
movie_genres = list(set(movie_genres_list))

In [56]:
movie_genres

['Horror',
 'Mystery',
 'Musical',
 'Fantasy',
 'Thriller',
 'Crime',
 'Music',
 'Action',
 'Adventure',
 'Animation',
 'History',
 'Sci-Fi',
 'Romance',
 'Drama',
 'News',
 'Biography',
 'Western',
 'Family',
 'War',
 'Comedy',
 'Documentary',
 'Sport']